#!/bin/bash

run_pip() {

    # Check for python
    if type_exists 'pip'; then
        e_header "Installing Python packages..."

        # List of python packages
        local packages="virtualenv virtualenvwrapper bpython pep8"

        # Install packages
        pip install $packages

        [[ $? ]] && e_success "Done"
    else
        printf "\n"
        e_error "Error: python not found."
        printf "Aborting...\n"
        exit
    fi

}
